name = "csoai-gspc-api"
main = "workers-api/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "csoai-gspc"
database_id = "c5ce60e7-4f59-4c87-9571-d55daa771fe2"
